// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Create the browser-only Supabase client. Avoid instantiating the client during
// SSR / Cloudflare Worker runtime module initialization because the browser
// client touches `localStorage` and requires build-time VITE_* vars. If the
// app imports this module on the server (SSR), export a stub that throws a
// clear error on use so accidental server-side usage of the browser client is
// obvious and fails fast.

const IS_BROWSER = typeof window !== "undefined" && typeof window.document !== "undefined";
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "") as string;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "") as string;

let _supabase: SupabaseClient<Database> | null = null;

function createBrowserSupabase(): SupabaseClient<Database> {
  if (_supabase) return _supabase;
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error(
      `[Supabase] Missing VITE_SUPABASE_* at build: VITE_SUPABASE_URL=${Boolean(
        SUPABASE_URL,
      )} VITE_SUPABASE_PUBLISHABLE_KEY=${Boolean(SUPABASE_PUBLISHABLE_KEY)}`,
    );
    throw new Error("Missing VITE_SUPABASE_* environment variables at build time");
  }

  _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return _supabase;
}

const ssrStub = new Proxy(
  {},
  {
    get() {
      throw new Error(
        "Browser Supabase client was used during SSR. Use src/integrations/supabase/client.server.ts instead.",
      );
    },
    apply() {
      throw new Error(
        "Browser Supabase client was used during SSR. Use src/integrations/supabase/client.server.ts instead.",
      );
    },
    construct() {
      throw new Error(
        "Browser Supabase client was used during SSR. Use src/integrations/supabase/client.server.ts instead.",
      );
    },
  },
) as unknown as SupabaseClient<Database>;

export const supabase: SupabaseClient<Database> = IS_BROWSER ? createBrowserSupabase() : ssrStub;
